### PR TITLE
Init sections

### PR DESCRIPTION
**Pull request by trungnd95**

### CODE REVIEW

**Comment by coderschoolreview** [comment]
@trungnd95 please update your README file :)

**Comment by trungnd95** [comment]
@coderschoolreview  yep. sure! =)) I'm done . 
--Trung Manucian --

**Comment by coderschoolreview** [comment]
Hi @trungnd95, sorry for the slow reply. We graded your homework but some of the reviews made on our system went missing. We just found out because we wanted to check your work before matching you with team members.

Goals of this homework:
- Learn how to define root path and custom paths. Use _path methods in controller and view files
- Use ActiveRecord querying with .where 
- Create multiple ActiveRecord models with different types of columns
- Sort items by using ActiveRecord's .order method (http://guides.rubyonrails.org/active_record_querying.html#ordering)
- Use ActionController's Flash (http://guides.rubyonrails.org/action_controller_overview.html#the-flash) to display success or failure notices

Great stuff:
- nice site layout and nice use of modals (popups)
- nice validations in the models
- nice use of nested routes and restricting routes using `only:`

Suggestions:
- please add padding to certain divs to make your elements stand out better
- you have a redundant/unused/incorrect  `get 'comments/create'` route
- you use `respond_to` but you're not supporting any format other than `format.html`. how do you use the `format.json` format in comments controller?
- i can't seem to place an order. clicking on link just provides an image as an order

Once again, nice job. Sorry for the missing comment on this. I'm sure you are much more familiar with the materials by now. Wish you all the best with the final project.

**Comment by trungnd95** [comment]
@coderschoolreview  To go to detail and order page. You can click on button under image, it like icon share. <i class="fa fa-share" aria-hidden="true"></i>
Thanks for your's recommend. I'll try my best !

**Pull request merged**
